#!/usr/bin/python

from pathlib import Path
from catparser.DisplayType import DisplayType

from generator import constant
from generator import util
from generator.models import array_generator
from generator.models import integer_generator
from generator.models import enum_generator
from generator.models import struct_generator
from generator.models import factory_generator

class Generator:
    @staticmethod
    def generate(astmodels, output):
        print(f'python catbuffer generator called with output: {output}')
        generate_files(astmodels, Path(output))

def generate_files(astmodels, output_directory: Path):
    
    util.update_int_type_of_struct(astmodels)
    output_directory.mkdir(exist_ok=True)

    with open(output_directory / 'models.rs', 'w', encoding='utf8', newline='') as output_file:
        import copy
        output = '''//! This file was generated by running script
            //! symbol/sdk/rust/scripts/run_catbuffer_generator.sh.
            
            use std::ops::{BitAnd, BitAndAssign, BitOr, BitOrAssign, BitXor, BitXorAssign, Not};
            pub use crate::symbol::models_header::*;\n\n
        '''

        for trait in constant.TRAITS_FOR_SIGN:
            type = util.get_type_of_trait(trait, astmodels)
            output += f'''
                pub trait Trait{util.snake_to_camel(trait)} {{
                fn get_{trait}(&self) -> &{type};
                fn set_{trait}(&mut self, {trait}: {type});
                }}
            '''
            
        factory_types = util.get_factory_types(astmodels)

        for astmodel in astmodels:
            if astmodel.name in ('Signature', 'PublicKey', 'VotingPublicKey'): 
                # See src/symbol/models_header.rs
                continue
            
            astmodel = copy.deepcopy(astmodel)
            output += util.header_for_each_astmodel(astmodel)
            if astmodel.name in factory_types:
                factory = astmodel
                factory_name = factory.name
                products = []
                for astmodel in astmodels:
                    if util.get_factory_type(astmodel) == factory_name:
                        products.append(copy.deepcopy(astmodel))
                output += factory_generator.generate_factory(factory, products)
            elif astmodel.display_type == DisplayType.STRUCT:
                output += struct_generator.generate_struct(astmodel)
            elif astmodel.display_type == DisplayType.ENUM:
                output += enum_generator.generate_enum(astmodel)
            elif astmodel.display_type == DisplayType.BYTE_ARRAY:
                output += array_generator.generate_bytearray(astmodel)
            elif astmodel.display_type == DisplayType.INTEGER:
                output += integer_generator.generate_integer(astmodel)
            else:
                raise 'Unexpected'

        output_file.write(output)

